In [1]:
from lnb_hakatons import PROJECT_DIR
import pandas as pd


DATA_DIR = "data/cleaned"

CLEAN_PATH = PROJECT_DIR / DATA_DIR / "recenzijas_clean.csv"
data_df = pd.read_csv(CLEAN_PATH)

CLEAN_PATH = PROJECT_DIR / DATA_DIR / "recenzijas_autori.csv"
autori_df = pd.read_csv(CLEAN_PATH)

CLEAN_PATH = PROJECT_DIR / DATA_DIR / "recenzijas_recenzenti.csv"
recenzenti_df = pd.read_csv(CLEAN_PATH)

CLEAN_PATH = PROJECT_DIR / DATA_DIR / "recenzijas_recenzetie_darbi.csv"
recenzetie_darbi_df = pd.read_csv(CLEAN_PATH)

CLEAN_PATH = PROJECT_DIR / DATA_DIR / "recenzijas_institucijas.csv"
institucijas_df = pd.read_csv(CLEAN_PATH)


FILTERED_OUT_PATH = PROJECT_DIR / DATA_DIR / "recenzijas_filtered_out.csv"
filtered_out_df = pd.read_csv(FILTERED_OUT_PATH).reset_index(drop=True)

DATA_DIR = PROJECT_DIR / "data/Mākslu kritika"
DATA_FILE = "cleaned-records-33-wide.csv"
original_data_df = pd.read_csv(DATA_DIR / DATA_FILE, sep=";")

/var/folders/ww/wjp3pnms1kzc2pfzj0tyl6zr0000gn/T/ipykernel_25350/694815458.py:8: DtypeWarning: Columns (36,37,38,92) have mixed types. Specify dtype option on import or set low_memory=False.
  data_df = pd.read_csv(CLEAN_PATH)
/var/folders/ww/wjp3pnms1kzc2pfzj0tyl6zr0000gn/T/ipykernel_25350/694815458.py:24: DtypeWarning: Columns (15,16,17,21,27,34,38,42,45,48,75) have mixed types. Specify dtype option on import or set low_memory=False.
  filtered_out_df = pd.read_csv(FILTERED_OUT_PATH).reset_index(drop=True)
/var/folders/ww/wjp3pnms1kzc2pfzj0tyl6zr0000gn/T/ipykernel_25350/694815458.py:28: DtypeWarning: Columns (6,17,44,46,47,48,60,62,63) have mixed types. Specify dtype option on import or set low_memory=False.
  original_data_df = pd.read_csv(DATA_DIR / DATA_FILE, sep=";")

## Data stats

In [58]:
len(original_data_df)

57921

In [42]:
original_data_df["PRIEKŠMETS - ŽANRS (655)"].value_counts().head(30)

PRIEKŠMETS - ŽANRS (655)
$$aIntervijas.                                         4292
$$aTeātra recenzijas.                                  3127
$$aGrāmatu apskati.                                    2783
$$aKinofilmu recenzijas.                               2424
$$aIzstādes.                                           2045
$$aMūzikas recenzijas.                                  904
$$aPersonālizstādes.                                    887
$$aZinātniskie raksti.                                  614
$$aIzstāžu recenzijas.                                  588
$$aOperas recenzijas.                                   394
$$aApskati un recenzijas.                               328
$$aKongresi, konferences utt.                           252
$$aBiogrāfijas.                                          87
$$aLatviešu esejas.                                      83
$$aLatviešu dokumentālā publicistika.                    74
$$aBaleta recenzijas.                                    62
$$aTelevīzijas raidījumu recenzijas.                     49
$$aDejas recenzijas.                                     43
$$aDokumentālā publicistika.                             43
$$aKrājumi.                                              33
$$aNekrologi.                                            25
$$aLatviešu bērnu dzeja$$xVēsture un kritika.            24
$$aLatviešu dzeja.                                       23
$$aLatgaliešu dzeja$$xVēsture un kritika.                21
$$aKrievu dzeja$$y21. gs.$$xVēsture un kritika.          18
$$aLatviešu fantastiskā proza$$xVēsture un kritika.      14
$$aLatviešu jaunatnes proza$$xVēsture un kritika.        13
$$aIgauņu dzeja$$xVēsture un kritika.                     9
$$aLatviešu ceļojumu apraksti.                            8
$$aLatviešu atmiņas.                                      7
Name: count, dtype: int64

In [46]:
no_genre = original_data_df["PRIEKŠMETS - ŽANRS (655)"].isna() & original_data_df["PRIEKŠMETS - ŽANRS - 2 (655)"].isna()
len(original_data_df[no_genre])

38417

In [43]:
len(original_data_df[no_genre]) / len(original_data_df)

0.6632654822948498

In [48]:
original_data_df[no_genre].iloc[-2]["RAKSTA NOSAUKUMS (245)"]

'$$aAtgādinājums par patiesi vērtīgo :$$bLatvijas Nacionālā opera un balets aicina uz jauniestudējumiem, izcilu solistu koncertiem un izrādēm ar operzvaigžņu dalību : [par Latvijas Nacionālās operas un baleta 2025./2026. g. sezonas aktualitātēm] /$$cIlze Auzāne ; tekstā stāsta Latvijas Nacionālās operas un baleta vadītājs Sandis Voldiņš, mākslinieciskais vadītājs Aivars Leimanis'

### Authors

In [ ]:
original_data_df

In [ ]:
isna = (
    data_df["AUTORS (100)_a"].isna() | (data_df["AUTORS (100)_4"] == "aqt")
) & (
    data_df["PAPILDRAKSTS (700)_a"].isna()]
 data_df["PAPILDRAKSTS (700)_a"].isna() & data_df["PAPILDRAKSTS - 2 (700)_a"].isna()
print(len(data_df[isna]))
len(data_df[~isna]) / len(data_df)

### Authors

55

0.9951567453328637

## Works

In [57]:
original_data_df["AVOTA NOSAUKUMS (773)"].value_counts().head(30)

AVOTA NOSAUKUMS (773)
$$tKroders.lv$$g(2023, 1. augusts), 2 lp.$$nTiešsaistes portāls.                                                                                                                                                                                     5
$$tKonteksts$$x2501-0220$$gNr.12 (2018, dec.), 13.lpp.                                                                                                                                                                                               5
$$tKonteksts$$x2501-0220$$gNr.12 (2018, dec.), 15.lpp.                                                                                                                                                                                               5
$$tKonteksts$$x2501-0220$$gNr.8 (2017, nov.), 10.lpp.                                                                                                                                                                                                4
$$tKonteksts$$x2501-0220$$gNr.9 (2018, sept.), 14.lpp.                                                                                                                                                                                               4
$$tKonteksts$$x2501-0220$$gNr.5 (2019, maijs), 10.lpp.                                                                                                                                                                                               4
$$tKonteksts$$x2501-0220$$gNr.9 (2018, sept.), 15.lpp.                                                                                                                                                                                               4
$$tJūrmalas pašvaldības informācijas biļetens$$gNr.53 (2015, 17.jūn.), 8.lpp.                                                                                                                                                                        4
$$tKonteksts$$x2501-0220$$gNr.1 (2019, janv.), 8.lpp. : ģīm.                                                                                                                                                                                         4
$$tJūrmalas pašvaldības informācijas biļetens$$gNr.54 (2015, 2.jūl.), 13.lpp.                                                                                                                                                                        4
$$tKonteksts$$x2501-0220$$gNr.12 (2019, dec.), 26.lpp.                                                                                                                                                                                               4
$$tJūrmalas Avīze$$gNr.12 (2016, 11.aug.), 11.lpp.                                                                                                                                                                                                   4
$$tJūrmalas pašvaldības informācijas biļetens$$gNr.66 (2016, 28.janv.), 11.lpp.                                                                                                                                                                      4
$$tLiesma$$x1691-0397$$gNr. 12 (2025, 29. janvāris), 5. lpp.                                                                                                                                                                                         4
$$tKonteksts$$x2501-0220$$gNr.7 (2017, okt.), 11.lpp.                                                                                                                                                                                                3
$$tLatvijas Avīze$$kPielikums "Kultūrzīmes", ISSN 2255-9078 ; # 3$$x1691-1229$$gNr. 18 (2021, 27. janvāris), 2. lpp.$$nTas pats tiešsaistes laikrakstā "Latvijas Avīze". - (Pielikums "Kultūrzīmes" ; # 3). – Nr. 18 (2021, 27. janvāris), 2. lp.    3
$$tJelgavas Vēstnesis$$x1691-4201$$gNr.7 (2016, 18.febr.), 8.lpp.                                                                                                                                                                                    3
$$tJūrmalas pašvaldības informācijas biļetens$$gNr.55 (2015, 16.jūl.), 9.lpp.                                                                                                                                                                        3
$$tVentas Balss$$x1407-9151$$gNr.62 (2018, 29.marts), [5.]lpp. : ģīm.$$nTas pats krievu val. laikr. "Вентас балсс" Nr.62 (2018, 29.marts), [5.]lpp. : ģīm.                                                                                           3
$$tTelevīzijas Programma$$x1407-2548$$gNr.19 (2016, 16./22.maijs), 6.lpp.                                                                                                                                                                            3
$$tLiesma$$x1691-0397$$gNr.91 (2017, 15.jūn.), 7.lpp.                                                                                                                                                                                                3
$$tJūrmalas pašvaldības informācijas biļetens$$gNr.56 (2015, 6.aug.), 7.lpp.                                                                                                                                                                         3
$$tKonteksts$$x2501-0220$$gNr.6 (2019, jūn.), 14.lpp.                                                                                                                                                                                                3
$$tKonteksts$$x2501-0220$$gNr.11 (2019, nov.), 24.lpp.                                                                                                                                                                                               3
$$tМиллион$$x1691-0230$$gN 47 (28 нояб. 2019), с.31.                                                                                                                                                                                                 3
$$tKonteksts$$x2501-0220$$gNr.7 (2018, jūl.), 13.lpp.                                                                                                                                                                                                3
$$tМиллион$$x1691-0230$$g№ 23 (10 июня 2021), 16. lpp.                                                                                                                                                                                               3
$$tKroders.lv$$g(2015, 9.nov.), 3 lp.$$nTiešsaistes portāls.                                                                                                                                                                                         3
$$tStars$$x1691-0958$$gNr. 40 (2024, 21. maijs), 9. lpp.$$nTas pats tiešsaistes laikrakstā "Stars" Nr. 40 (2024, 21. maijs), 9. lp.                                                                                                                  3
$$tJūrmalas pašvaldības informācijas biļetens$$gNr.47 (2015, 12.marts), 8.lpp.                                                                                                                                                                       3
Name: count, dtype: int64

np.int64(56618)

KeyError: 'PRIEKŠMETS - ŽANRS (655) - 2'

In [21]:
autori_df[autori_df.Autors.str.contains("..")]

,ID,Autors,Autors un gadi
0,672515,Dace Priede,Dace Priede 1954-
1,672515,Johann Schwerin,Johann Schwerin 1592-1637
2,4217490,Robert Bolt,Robert Bolt 1924-1995
3,4217490,Сергей Анатольевич Голомазов,Сергей Анатольевич Голомазов 1961-
4,4217380,Paavo Matsin,Paavo Matsin 1970-
...,...,...,...
18944,4252341,Alexandra Coelho Ahndoril,Alexandra Coelho Ahndoril 1966-
18945,4336187,Maikls Spicers,Maikls Spicers
18946,4336187,Renāte Punka,Renāte Punka 1965-
18947,4336343,Олег Мальцев,Олег Мальцев
18948,4336343,Ирина Лопатюк,Ирина Лопатюк

In [ ]:
autori_df

,ID,Autors,Autors un gadi
0,672515,Dace Priede,Dace Priede 1954-
1,672515,Johann Schwerin,Johann Schwerin 1592-1637
2,4217490,Robert Bolt,Robert Bolt 1924-1995
3,4217490,Сергей Анатольевич Голомазов,Сергей Анатольевич Голомазов 1961-
4,4217380,Paavo Matsin,Paavo Matsin 1970-
...,...,...,...
18944,4252341,Alexandra Coelho Ahndoril,Alexandra Coelho Ahndoril 1966-
18945,4336187,Maikls Spicers,Maikls Spicers
18946,4336187,Renāte Punka,Renāte Punka 1965-
18947,4336343,Олег Мальцев,Олег Мальцев
18948,4336343,Ирина Лопатюк,Ирина Лопатюк

In [2]:
# startified sample, 5 items from each Recenzijas tips
seed = 42
samples = []
for tips in data_df["Recenzijas tips"].unique():
    samples.append(data_df.query("`Recenzijas tips` == @tips").sample(5))
samples = pd.concat(samples, ignore_index=True)
len(samples)

50

In [4]:
samples.to_csv(PROJECT_DIR / DATA_DIR / "recenzijas_sample.csv", index=False)

In [121]:
pd.set_option('display.max_colwidth', None)
col = "PRIEKŠMETS - INSTITŪCIJA - 3 (610)"
col2 = "PRIEKŠMETS - INSTITŪCIJA - 4 (610)"
col3 = "RAKSTA NOSAUKUMS (245)"
original_data_df[~original_data_df[col2].isna()][[col3, col, col2]]

,RAKSTA NOSAUKUMS (245),PRIEKŠMETS - INSTITŪCIJA - 3 (610),PRIEKŠMETS - INSTITŪCIJA - 4 (610)
70,"$$aPieejamības manifestācija :$$bceļojums pa Latvijas dizaina sasniegumu un nākotnes vīziju maršrutiem : [par izstādi ""Reputācija"" Latvijas Nacionālajā bibliotēkā, izstādi ""Humanizācija"" un pasākumu ""Modes manifestācija"" Dekoratīvās mākslas un dizaina muzejā, izstādi ""Informācija"" Latvijas Mākslas akadēmijā, izstādi ""Situācija"" Latgales vēstniecībā ""Gors"" Rēzeknē, pasākumu ""Dizaina pastaiga"" Rīgas pilsētvidē : sakarā ar ekspozīciju un notikumu ciklu ""Dizaina manifestācija""] /$$cIlze Auzāne",$$aLatvijas Mākslas akadēmija.,"$$aLatgales vēstniecība ""GORS""."
230,$$aMinistru kabineta sēdes protokols :$$bLR Ministru kabineta sēdes protokols Nr.5. : Rīgā 2015.g. 27.janv.,$$aEuropean Space Agency.,$$aEiropas Cilvēktiesību tiesa.
287,$$a[Divpadsmitās Saeimas stenogrammas] :$$b[2015.g. ziemas sesija].,$$aLatvijas Republikas Iekšlietu ministrija$$xIerēdņi un darbinieki.,$$aRail Baltica (projekts)
591,"$$aLatvijas uzņēmēju atsauksmes par izstādi Zaļā nedēļa 2015 :$$b[par dalību starptautiskajā pārtikas, lauksaimniecības un dārzkopības izstādē ""Zaļā nedēļa 2015"" Berlīnē] /$$ctekstā stāsta SIA ""Antaris"" konditorejas fabrikas ""Mõra"" komercdirektore Valentīna Krumpāne, SIA ""Perfekto"" gardumu ražotnes direktors Haralds Salmiņš, zemnieku saimniecības ""Muižgaļi"" saimnieks Jānis Vītolbergs, ekoloģiskā gaļas zīmola ""Baudi"" pārstāve Agnese Buka, vīna darītavas ""Ledus vīni"" pārstāve Ilze Saleniece, bišu dravas ""Kalnu medus"" produkcijas pārstāvis Sandris Akmans, SIA ""Rāmkalni Nordeco"" pārstāve Sanda Auziņa, stenda ""Pļava"" pārstāve Linda Bille, stenda ""Dārzs un Drava"" pārstāve Aiga Kraukle",$$aPerfecto$$g(uzņēmums),$$aLāči$$g(uzņēmums)
658,"$$aIzstādē Balttour - veiksmīgi :$$b[par Kuldīgas un Alsungas novadu pārstāvju piedalīšanos 22.starptautiskajā tūrisma izstādē - gadatirgū ""Balttour 2015"" Starptautiskajā izstāžu centrā Ķīpsalā] /$$cDaina Tāfelberga, Juris Lipsnis ; tekstā stāsta Kuldīgas Aktīvās atpūtas centra direktors Artis Gustovskis, Kuldīgas novada muzeja sabiedrisko attiecību speciāliste Krista Jansone, lauksaimniecības pakalpojumu kooperatīvās sabiedrības ""Kuldīgas labumi"" koordinatore Līga Raituma, Alsungas muzeja vadītāja Inga Bredovska",$$aAlsungas Novada muzejs.,$$aSuitu maize (uzņēmums)
...,...,...,...
57820,"$$a""Kurš būs tik drosmīgs pateikt?"" :$$b[saruna ar bijušo Latvijas Republikas kultūras ministru, bijušo bijis rokgrupas ""Pērkons"" solistu, operdziedātāju : par gaidāmo festivālu ""Zibens pa dibenu"" 15. augustā rokgrupas ""Pērkons"" koncerta Ogres estrādē pirms četrdesmit gadiem atcerei, kultūras norisēm Latvijā, bērnu kultūrizglītības politiku, problēmām un nacionālās apvienības ""Visu Latvijai!""—""Tēvzemei un Brīvībai/LNNK"""" darbības plāniem] /$$cNauris Puntulis ; pierakstīja Egils Līcītis",$$aLatvijas Nacionālā opera un balets.,"$$aNacionālā apvienība ""Visu Latvijai!""—""Tēvzemei un Brīvībai/LNNK""."
57845,$$aKā no pārpilnības raga :$$b[par gaidāmās teātra sezonas aktualitātēm] /$$cUndīne Adamaite,$$aDailes teātris.,$$aLatvijas Nacionālais teātris.
57875,"$$aMazie dziedātāji iedzied pavasari Cesvainē :$$b[par pirmsskolas vecuma bērnu vokālo ansambļu u ""Pavasara raibumiņi"" (Madonas novads) : Cesvaines Kultūras nama vadītājas raksts] /$$cKristīne Aumele",$$aPriedīte$$g(Madonas pilsētas pirmsskolas izglītības iestāde),$$aPasaciņa$$g(Praulienas pagasta pirmsskolas izglītības iestāde)
57898,$$aDraugi! Būs slikti! :$$b[par jaunās teātra sezonas jauniestudējumiem Latvijas teātros] /$$cZane Radzobe,$$aValmieras Drāmas teātris.,$$aJaunais Rīgas teātris (1992-)
57901,$$aNo lībiešiem līdz kvadroberiem :$$b[par nevalstisko teātru gaidāmo sezonu] /$$cAtis Rozentāls,$$aKvadrifrons (teātra trupa),$$aĢertrūdes ielas teātris.

In [83]:
data_df[data_df.Autori.isna()]

,ID,Recenzenti (list),Recenzenti,Recenzenti un gadi (list),Recenzenti un gadi,Avots,Temats,Gads,Recenzijas virsraksts,Galvenais autors,...,RECENZĒTĀ FILMA VAI IZRĀDE - 4 (630),RECENZĒTĀ FILMA VAI IZRĀDE -2 (630),VALODAS KODS (041),ĢEOGRĀFISKAIS NOSAUKUMS (651),ĢEOGRĀFISKAIS NOSAUKUMS - 2 (651),ĢEOGRĀFISKAIS NOSAUKUMS - 3 (651),ĢEOGRĀFISKAIS NOSAUKUMS - 4 (651),ĢEOGRĀFISKAIS NOSAUKUMS - 5 (651),(630)_director,AUTORS_ad
3232,3734207,['Māris Zanders'],Māris Zanders,['Māris Zanders 1970-'],Māris Zanders 1970-,Diena,Krievi,2016,Paralēlās pasaules un neizmantotais resurss,Visi,...,NaN,NaN,$$alav,NaN,NaN,NaN,NaN,NaN,NaN,Māris Zanders 1970-
4716,4422033,['Rasa Bugavičute-Pēce'],Rasa Bugavičute-Pēce,['Rasa Bugavičute-Pēce 1988-'],Rasa Bugavičute-Pēce 1988-,Kroders.lv,Teātri,2025,Un ko man ar to visu iesākt? : pārdomas par sp...,NaN,...,NaN,NaN,NaN,$$aKlaipēda (Lietuva),NaN,NaN,NaN,NaN,NaN,Rasa Bugavičute-Pēce 1988-
4717,4141089,['Anda Rožukalne'],Anda Rožukalne,['Anda Rožukalne 1965-'],Anda Rožukalne 1965-,Latvijas Avīze,Interneta televīzija,2021,"Parunāsim par sarunām: mazāk šova, vairāk satu...",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Anda Rožukalne 1965-
4720,4139717,['Valda Čakare'],Valda Čakare,['Valda Čakare 1953-'],Valda Čakare 1953-,Kroders.lv,Teātra iestudējumi,2021,Totāls mākslas darbs epidēmijas laikā : par ne...,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Valda Čakare 1953-
4734,4395764,['Stella Pelše'],Stella Pelše,['Stella Pelše 1972-'],Stella Pelše 1972-,Diena,Mākslinieki,2025,Reālisma kapsula laikmetīgās šaubās : sakarā a...,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Stella Pelše 1972-
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11325,4153880,['Lauma Malnace'],Lauma Malnace,['Lauma Malnace 1992-'],Lauma Malnace 1992-,Delfi.lv,Mūzikas festivāli,2020,"Autentiskums un sauciens brīvībai. Festivāla ""...",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Lauma Malnace 1992-
11336,3888384,['Lauma Mellēna-Bartkeviča'],Lauma Mellēna-Bartkeviča,['Lauma Mellēna-Bartkeviča 1981-'],Lauma Mellēna-Bartkeviča 1981-,Neatkarīgā Rīta Avīze Latvijai,Koncerti (pasākums),2018,Simfoniskais skats: plašumā un nākotnē : par 1...,NaN,...,NaN,NaN,$$alav,NaN,NaN,NaN,NaN,NaN,NaN,Lauma Mellēna-Bartkeviča 1981-
11340,3776491,['Bārbala Simsone'],Bārbala Simsone,['Bārbala Simsone 1978-'],Bārbala Simsone 1978-,Krustpunkti: kultūras un mākslas pētījumi,NaN,2016,Zinātniskās fantastikas žanrs latviešu literatūrā,NaN,...,NaN,NaN,$$alav$$beng,NaN,NaN,NaN,NaN,NaN,NaN,Bārbala Simsone 1978-
11342,3891474,['Bārbala Simsone'],Bārbala Simsone,['Bārbala Simsone 1978-'],Bārbala Simsone 1978-,Krustpunkti: kultūras un mākslas pētījumi,NaN,2017,Ceļošana laikā latviešu fantastu interpretācij...,NaN,...,NaN,NaN,$$alav$$beng,NaN,NaN,NaN,NaN,NaN,NaN,Bārbala Simsone 1978-
11343,4005186,['Armands Znotiņš'],Armands Znotiņš,['Armands Znotiņš'],Armands Znotiņš,Latvijas Avīze,Mūzikas festivāli,2019,Venēcijas un Meksikas baroks Rīgā : par Starpt...,NaN,...,NaN,NaN,$$alav,NaN,NaN,NaN,NaN,NaN,NaN,Armands Znotiņš

In [73]:
from ast import literal_eval

(
    data_df
    .assign(**{
        "Recenzenti un gadi (list)": lambda x: x["Recenzenti un gadi (list)"].apply(literal_eval),
        "Autori un gadi (list)": lambda x: x["Autori un gadi (list)"].apply(literal_eval),
    })
    .assign(lens = lambda x: x["Autori un gadi (list)"].apply(lambda x: len(x) if isinstance(x, list) else 0))
    .query("lens == 0")
)[["Galvenais autors", "Autori un gadi (list)"]]

      Galvenais autors Autori un gadi (list)
3232              Visi                    []
4716               NaN                    []
4717               NaN                    []
4718               NaN                    []
4719               NaN                    []
...                ...                   ...
11351              NaN                    []
11352              NaN                    []
11353              NaN                    []
11354              NaN                    []
11355              NaN                    []

[4618 rows x 2 columns]

In [76]:
data_df[data_df.Autori.isna()]

,ID,Recenzenti (list),Recenzenti,Recenzenti un gadi (list),Recenzenti un gadi,Avots,Temats,Gads,Recenzijas virsraksts,Galvenais autors,...,RECENZĒTĀ FILMA VAI IZRĀDE - 4 (630),RECENZĒTĀ FILMA VAI IZRĀDE -2 (630),VALODAS KODS (041),ĢEOGRĀFISKAIS NOSAUKUMS (651),ĢEOGRĀFISKAIS NOSAUKUMS - 2 (651),ĢEOGRĀFISKAIS NOSAUKUMS - 3 (651),ĢEOGRĀFISKAIS NOSAUKUMS - 4 (651),ĢEOGRĀFISKAIS NOSAUKUMS - 5 (651),(630)_director,AUTORS_ad
3232,3734207,['Māris Zanders'],Māris Zanders,['Māris Zanders 1970-'],Māris Zanders 1970-,Diena,Krievi,2016,Paralēlās pasaules un neizmantotais resurss,Visi,...,NaN,NaN,$$alav,NaN,NaN,NaN,NaN,NaN,NaN,Māris Zanders 1970-
4716,4422033,['Rasa Bugavičute-Pēce'],Rasa Bugavičute-Pēce,['Rasa Bugavičute-Pēce 1988-'],Rasa Bugavičute-Pēce 1988-,Kroders.lv,Teātri,2025,Un ko man ar to visu iesākt? : pārdomas par sp...,NaN,...,NaN,NaN,NaN,$$aKlaipēda (Lietuva),NaN,NaN,NaN,NaN,NaN,Rasa Bugavičute-Pēce 1988-
4717,4141089,['Anda Rožukalne'],Anda Rožukalne,['Anda Rožukalne 1965-'],Anda Rožukalne 1965-,Latvijas Avīze,Interneta televīzija,2021,"Parunāsim par sarunām: mazāk šova, vairāk satu...",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Anda Rožukalne 1965-
4718,4066243,['Anna Andersone'],Anna Andersone,['Anna Andersone 1991-'],Anna Andersone 1991-,Kroders.lv,Teātra iestudējumi,2017,Vai viegli būt jaunam? : dramaturģes Justīnes ...,NaN,...,NaN,NaN,$$alav,NaN,NaN,NaN,NaN,NaN,NaN,Anna Andersone 1991-
4719,4422030,['Edvards Bruss'],Edvards Bruss,['Edvards Bruss'],Edvards Bruss,Kroders.lv,Teātra iestudējumi,2025,Nāve ir sieviete baltā kleitā : par spāņu raks...,NaN,...,NaN,NaN,NaN,$$aRīga (Latvija),"$$aValmiera (Valmieras novads, Latvija)",NaN,NaN,NaN,NaN,Edvards Bruss
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11351,3874413,[],NaN,[],NaN,Latvijas Arhīvi,Lauksaimniecības vēsture,2017,"""2017.gadā apgādā..."".",NaN,...,NaN,NaN,$$alav,NaN,NaN,NaN,NaN,NaN,NaN,
11352,4252341,[],NaN,[],NaN,Ziņnesis / Jānis Roze,Zviedru autori,2019,Zviedru literatūras zelta pāris : par zviedru ...,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,
11353,4279463,[],NaN,[],NaN,Avīzes Nosaukums,Revolūcijas.,2022,Ievads lēnajai revolūcijai : eseja.,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,
11354,4336187,[],NaN,[],NaN,Ziņnesis / Jānis Roze,Mūzika,2023,Homo musicus. Dzīvības vēsture uz Zemes : par ...,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,
11355,4336343,[],NaN,[],NaN,Гранит науки = Granite of Science,Prāts.,2023,"Написана и издана монография ""Работа разума в ...",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,

In [12]:
# 
(
    original_data_df[["RECENZĒTĀ FILMA VAI IZRĀDE (630)"]]
    .copy()
    .assign(lens=lambda x: x["RECENZĒTĀ FILMA VAI IZRĀDE (630)"].str.len())
    .sort_values(by="lens", ascending=False)
).iloc[10]["RECENZĒTĀ FILMA VAI IZRĀDE (630)"]

'$$aBez morāles. Ar lellēm$$g(teātra izrāde : Mārtiņš Eihe, Edgars Kaufelds, Edgars Niklasons, Vija Blūzma).$$f2022'

In [4]:
list(original_data_df.columns)

['ID',
 'NBA01-ID (001)',
 'UDK (080)',
 'AUTORS (100)',
 'RAKSTA NOSAUKUMS (245)',
 'GADS (008)',
 'ILUSTRĀCIJAS (300)',
 'SATURA VEIDS (336)',
 'SATURA VEIDS 2 (336)',
 'PRIEKŠMETS - PERSONA (600)',
 'PRIEKŠMETS - PERSONA 2 (600)',
 'PRIEKŠMETS - PERSONA - 3 (600)',
 'PRIEKŠMETS - TEMATS (650)',
 'PRIEKŠMETS - TEMATS 2 (650)',
 'PRIEKŠMETS - TEMATS - 3 (650)',
 'ĢEOGRĀFISKAIS NOSAUKUMS (651)',
 'PRIEKŠMETS - ŽANRS (655)',
 'RECENZĒTAIS IZDEVUMS (787)',
 'AVOTA NOSAUKUMS (773)',
 'KODĒTS DATĒJUMS (904)',
 'VALODAS KODS (041)',
 'PRIEKŠMETS - INSTITŪCIJA (610)',
 'ELEKTRONISKĀ ADRESE (856)',
 'ELEKTRONISKĀ ADRESE - 2 (856)',
 'UDK - 2 (080)',
 'PRIEKŠMETS - TEMATS - 4 (650)',
 'LURSOFT ID (905)',
 'RECENZĒTĀ FILMA VAI IZRĀDE (630)',
 'PRIEKŠMETS - PERSONA - 4 (600)',
 'PRIEKŠMETS - PERSONA - 5 (600)',
 'PAPILDRAKSTS (700)',
 'PAPILDRAKSTS - 2 (700)',
 'PRIEKŠMETS - INSTITŪCIJA - 2 (610)',
 'RECENZĒTAIS IZDEVUMS (500)',
 'PRIEKŠMETS - PASĀKUMS (611)',
 'PRIEKŠMETS - PASĀKUMS - 2 (611)',
 'PRIEKŠMETS - PASĀKUMS - 3 (611)',
 'PRIEKŠMETS - TEMATS - 5 (650)',
 'PAPILDRAKSTS - 3 (700)',
 'PAPILDRAKSTS - 4 (700)',
 'PAPILDRAKSTS - 5 (700)',
 'PRIEKŠMETS - ŽANRS - 2 (655)',
 'PRIEKŠMETS - INSTITŪCIJA - 3 (610)',
 'PRIEKŠMETS - INSTITŪCIJA - 4 (610)',
 'PRIEKŠMETAM PIEVIENOTĀ ENTĪTE (688)',
 'RECENZĒTĀ FILMA VAI IZRĀDE - 2 (630)',
 'RECENZĒTĀ FILMA VAI IZRĀDE - 3 (630)',
 'RECENZĒTĀ FILMA VAI IZRĀDE - 4 (630)',
 'RECENZĒTĀ FILMA VAI IZRĀDE -2 (630)',
 'ĢEOGRĀFISKAIS NOSAUKUMS - 2 (651)',
 'NEKONTROLĒTS PERSONAS VĀRDS (720)',
 'NEKONTROLĒTS PERSONAS VĀRDS - 2 (720)',
 'NEKONTROLĒTS PERSONAS VĀRDS - 3 (720)',
 'NEKONTROLĒTS PERSONAS VĀRDS - 4 (720)',
 'ELEKTRONISKĀ ADRESE - 3 (856)',
 'PRIEKŠMETS - INSTITŪCIJA - 2 (610)2',
 'ĢEOGRĀFISKAIS NOSAUKUMS - 3 (651)',
 'ĢEOGRĀFISKAIS NOSAUKUMS - 4 (651)',
 'BIBLIOGRĀFIJA (504)',
 'NEKONTROLĒTS PERSONAS VĀRDS - 5 (720)',
 'PRIEKŠMETS - PASĀKUMS - 4 (611)',
 'ĢEOGRĀFISKAIS NOSAUKUMS - 5 (651)',
 'RECENZĒTAIS IZDEVUMS - 2 (787)',
 'PRIEKŠMETAM PIEVIENOTĀ ENTĪTE - 2 (688)']

In [16]:
data_df

            ID                     Autors                   Autors un gadi
0       672515                Dace Priede                Dace Priede 1954-
1       672515            Johann Schwerin        Johann Schwerin 1592-1637
2      4217611              Gundega Repše              Gundega Repše 1960-
3      3917000                Elīna Cērpa                      Elīna Cērpa
4      3917000          Marina Brusņikina                Marina Brusņikina
...        ...                        ...                              ...
19438  4336187               Renāte Punka               Renāte Punka 1965-
19439  4252341                Lars Kepler                      Lars Kepler
19440  4252341  Alexandra Coelho Ahndoril  Alexandra Coelho Ahndoril 1966-
19441  4340615       Daina Jansone-Treice       Daina Jansone-Treice 1948-
19442  4279463            Pērsijs Šellijs        Pērsijs Šellijs 1792-1822

[19443 rows x 3 columns]

In [134]:
list(data_df.columns)

['ID',
 'Recenzenti (list)',
 'Recenzenti',
 'Recenzenti un gadi (list)',
 'Recenzenti un gadi',
 'Avots',
 'Temats',
 'Gads',
 'Recenzijas virsraksts',
 'Galvenais autors',
 'Galvenais autors (600)',
 'Galvenais autors un gadi (600)',
 'Autori (list)',
 'Autori',
 'Autori un gadi (list)',
 'Autori un gadi',
 'Recenzētais darbs',
 'Saistītā organizācija vai notikums',
 'Recenzijas tips',
 'AUTORS (100)_4',
 'AUTORS (100)_a',
 'AUTORS (100)_c',
 'AUTORS (100)_d',
 'PAPILDRAKSTS (700)_4',
 'PAPILDRAKSTS (700)_a',
 'PAPILDRAKSTS (700)_c',
 'PAPILDRAKSTS (700)_d',
 'PAPILDRAKSTS - 2 (700)_4',
 'PAPILDRAKSTS - 2 (700)_a',
 'PAPILDRAKSTS - 2 (700)_c',
 'PAPILDRAKSTS - 2 (700)_d',
 'RAKSTA NOSAUKUMS (245)_a',
 'RAKSTA NOSAUKUMS (245)_b',
 'RAKSTA NOSAUKUMS (245)_c',
 'RECENZĒTAIS IZDEVUMS (787)_a',
 'RECENZĒTAIS IZDEVUMS (787)_t',
 'RECENZĒTAIS IZDEVUMS (787)_d',
 'RECENZĒTAIS IZDEVUMS (500)_a',
 'RECENZĒTĀ FILMA VAI IZRĀDE (630)_a',
 'RECENZĒTĀ FILMA VAI IZRĀDE (630)_g',
 'RECENZĒTĀ FILMA VAI IZRĀDE (630)_f',
 'AVOTA NOSAUKUMS (773)_g',
 'ELEKTRONISKĀ ADRESE (856)_u',
 'PRIEKŠMETS - ŽANRS (655)_a',
 'PRIEKŠMETS - ŽANRS (655)_x',
 'PRIEKŠMETS - ŽANRS - 2 (655)_a',
 'PRIEKŠMETS - ŽANRS - 2 (655)_x',
 'PRIEKŠMETS - INSTITŪCIJA (610)_a',
 'PRIEKŠMETS - INSTITŪCIJA (610)_g',
 'NEKONTROLĒTS PERSONAS VĀRDS (720)_4',
 'NEKONTROLĒTS PERSONAS VĀRDS (720)_a',
 'NEKONTROLĒTS PERSONAS VĀRDS (720)_c',
 'NEKONTROLĒTS PERSONAS VĀRDS (720)_d',
 'NEKONTROLĒTS PERSONAS VĀRDS - 2 (720)_4',
 'NEKONTROLĒTS PERSONAS VĀRDS - 2 (720)_a',
 'NEKONTROLĒTS PERSONAS VĀRDS - 2 (720)_c',
 'NEKONTROLĒTS PERSONAS VĀRDS - 2 (720)_d',
 'NEKONTROLĒTS PERSONAS VĀRDS - 3 (720)_4',
 'NEKONTROLĒTS PERSONAS VĀRDS - 3 (720)_a',
 'NEKONTROLĒTS PERSONAS VĀRDS - 3 (720)_d',
 'NEKONTROLĒTS PERSONAS VĀRDS - 4 (720)_4',
 'NEKONTROLĒTS PERSONAS VĀRDS - 4 (720)_a',
 'NEKONTROLĒTS PERSONAS VĀRDS - 4 (720)_d',
 'NEKONTROLĒTS PERSONAS VĀRDS - 5 (720)_4',
 'NEKONTROLĒTS PERSONAS VĀRDS - 5 (720)_a',
 'NEKONTROLĒTS PERSONAS VĀRDS - 5 (720)_d',
 'PRIEKŠMETS - PERSONA (600)_a',
 'PRIEKŠMETS - PERSONA (600)_c',
 'PRIEKŠMETS - PERSONA (600)_d',
 'PRIEKŠMETS - PERSONA - 2 (600)_a',
 'PRIEKŠMETS - PERSONA - 2 (600)_c',
 'PRIEKŠMETS - PERSONA - 2 (600)_d',
 'PRIEKŠMETS - PERSONA - 3 (600)_a',
 'PRIEKŠMETS - PERSONA - 3 (600)_c',
 'PRIEKŠMETS - PERSONA - 3 (600)_d',
 'PRIEKŠMETS - PERSONA - 4 (600)_a',
 'PRIEKŠMETS - PERSONA - 4 (600)_c',
 'PRIEKŠMETS - PERSONA - 4 (600)_d',
 'PRIEKŠMETS - PERSONA - 5 (600)_a',
 'PRIEKŠMETS - PERSONA - 5 (600)_c',
 'PRIEKŠMETS - PERSONA - 5 (600)_d',
 'ELEKTRONISKĀ ADRESE - 2 (856)',
 'ELEKTRONISKĀ ADRESE - 3 (856)',
 'KODĒTS DATĒJUMS (904)',
 'LURSOFT ID (905)',
 'NBA01-ID (001)',
 'PAPILDRAKSTS - 3 (700)',
 'PAPILDRAKSTS - 4 (700)',
 'PAPILDRAKSTS - 5 (700)',
 'PRIEKŠMETAM PIEVIENOTĀ ENTĪTE (688)',
 'PRIEKŠMETAM PIEVIENOTĀ ENTĪTE - 2 (688)',
 'PRIEKŠMETS - INSTITŪCIJA - 2 (610)',
 'PRIEKŠMETS - INSTITŪCIJA - 2 (610)2',
 'PRIEKŠMETS - INSTITŪCIJA - 3 (610)',
 'PRIEKŠMETS - INSTITŪCIJA - 4 (610)',
 'PRIEKŠMETS - PASĀKUMS (611)',
 'PRIEKŠMETS - PASĀKUMS - 2 (611)',
 'PRIEKŠMETS - PASĀKUMS - 3 (611)',
 'PRIEKŠMETS - PASĀKUMS - 4 (611)',
 'PRIEKŠMETS - TEMATS - 3 (650)',
 'PRIEKŠMETS - TEMATS - 4 (650)',
 'PRIEKŠMETS - TEMATS - 5 (650)',
 'PRIEKŠMETS - TEMATS 2 (650)',
 'RECENZĒTAIS IZDEVUMS - 2 (787)',
 'RECENZĒTĀ FILMA VAI IZRĀDE - 2 (630)',
 'RECENZĒTĀ FILMA VAI IZRĀDE - 3 (630)',
 'RECENZĒTĀ FILMA VAI IZRĀDE - 4 (630)',
 'RECENZĒTĀ FILMA VAI IZRĀDE -2 (630)',
 'VALODAS KODS (041)',
 'ĢEOGRĀFISKAIS NOSAUKUMS (651)',
 'ĢEOGRĀFISKAIS NOSAUKUMS - 2 (651)',
 'ĢEOGRĀFISKAIS NOSAUKUMS - 3 (651)',
 'ĢEOGRĀFISKAIS NOSAUKUMS - 4 (651)',
 'ĢEOGRĀFISKAIS NOSAUKUMS - 5 (651)',
 '(630)_director',
 'AUTORS_ad']

In [131]:
data_df[["visi_recenzenti", "visi_autori_gadi"]]

,visi_recenzenti,visi_autori_gadi
0,['Eva Mārtuža'],"['Dace Priede 1954-', 'Johann Schwerin 1592-1637']"
1,['Līga Ulberte'],"['Антон Павлович Чехов 1860-1904', 'Regnārs Vaivars 1973-']"
2,['Elvīra Bloma'],['Jānis Rokpelnis 1945-']
3,['Ieva Rodiņa'],"['Viesturs Kairišs 1971-', 'Juliusz Słowacki 1809-1849']"
4,['Jūlija Dibovska'],['Сергій Вікторович Жадан 1974-']
...,...,...
11351,[],"['Олег Мальцев', 'Ирина Лопатюк']"
11352,['Andra Silapētere'],[]
11353,['Uldis Rudaks'],"['Arvydas Kazlauskas 1982-', 'Ļudis Mockūns']"
11354,['Михайло Анатолійович Мінаков'],"['Максим Лепский', 'Олег Мальцев', 'Алексей Самсонов']"
11355,['Ingmāra Balode'],['Julian Tuwim 1894-1953']

In [60]:
# list(original_data_df.columns)

In [ ]:
data_df

In [113]:
pd.set_option('display.max_colwidth', 500)
filtered_out_df[filtered_out_df["RECENZĒTĀ FILMA VAI IZRĀDE (630)_a"].isna()==False][[
    "AUTORS (100)_a",
    "RECENZĒTĀ FILMA VAI IZRĀDE (630)_a",
    "RAKSTA NOSAUKUMS (245)_a",
    "RAKSTA NOSAUKUMS (245)_b",
]]

,AUTORS (100)_a,RECENZĒTĀ FILMA VAI IZRĀDE (630)_a,RAKSTA NOSAUKUMS (245)_a,RAKSTA NOSAUKUMS (245)_b
3,"Подлубный, Виктор",The Great Waltz,"Наш ""Большой вальс"" :","[о рос. эмигрантах, амер. композиторе Дмитрие Тёмкине (1894-1979), амер. кинооператоре Джозефе Руттенберге (1889-1983), исполн. гл. ролей актере Фернане Гравее и актрисах Милице Корьюс (1908-1980) и Луизе Райнер в амер. худож. фильме ""Большой вальс"" (режиссер Жульен Дювивье : 1896-1967)] /"
37,"Ločmelis, Ziedonis,",Džimlai Rūdi rallallā,Ziedonis Ločmelis un Lielais Kristaps :,"[saruna ar Garkalnes novada jaunsargu instruktoru, kalēju pulciņa vadītāju, bijušo Nacionālo bruņoto spēku virsseržantu : sakarā ar Latvijas nacionālā filmu festivāla ""Lielais Kristaps"" balvas iegūšanu kā labākais otrā plāna aktieris par virsseržanta tēlojumu spēlfilmā ""Džimlai rūdi rallallā"" (rež. Māris Putniņš un Jānis Cimmermanis)] /"
51,"Bagirovs, Vladimirs,",Robina Huda bultas,Я поля влюблённым постелю.. :,"[о выплате гонорара рос. поэту и певцу Владимиру Высоцкому (1938-1980) за песни к художеств. фильму Риж. киностудии ""Стрелы Робин Гуда"" (режиссер Сергей Тарасов)] /"
70,"Ēķis, Andrejs,",Nameja gredzens,Latvija nebeidzas pie Jēkabpils :,"[saruna ar kinoprod. : sakarā ar darbu pie jaunās spēlfilmas ""Nameja gredzens"" uzņemšanu kopā ar rež. Aigaru Graubu] /"
86,"Звягинцев, Андрей Петрович,",Левиафан,"Это история о человеческом уделе, а не политике :","[беседа с рос. режиссером художеств. фильма ""Левиафан""] /"
...,...,...,...,...
46478,"Jerohomovičs, Jegors",Marija Stjuarte,Attiecības bez tuvības :,"[par itāliešu komponista Gaetāno Doniceti operas ""Marija Stjuarte"" jauniestudējumu (režisors Ulrihs Raše) Zalcburgas festivāla programmā (Austrija)] /"
46515,"Jance, Diāna,",Bezgalīgais ritums,"Straumēnu DNS ""Billītēs"" :","[par Cēsu Mazo teātri, izrādi ""Bezgalīgais ritums"" (režisore Liena Šmukste) pēc rakstnieka Edvarta Virzas poēmas ""Straumēni"" motīviem] /"
46521,"Leikuma, Iveta,",Skroderdienas Silmačos,Skroderdienas Krāslavā: Blaumaņa gars dzīvo arī šodien :,"[par dramaturga Rūdolfa Blaumaņa lugas ""Skroderdienas Silmačos"" brīvdabas iestudējumu (režisors Gundars Silakaktiņš) Krāslavas estrādē] /"
46528,"Wilson, Robert,",Dorians,Vienīgā pastāvīgā lieta ir pārmaiņas :,"[par iestudējumu ""Dorians"" Kauņas Nacionālajā Drāmas teātrī (Lietuva), darba metodēm un radošuma avotiem : saruna ar amerikāņu teātra un operas režisoru, dramaturgu un vizuālo mākslinieku (1941–2025)] /"
46534,"Treinis, Toms,",NACHTLAND,Kurš metīs pirmo akmeni? :,"[saruna ar teātra režisoru : sakarā ar vācu autora Mariusa fon Maienburga lugas ""NACHTLAND"" pirmizrādi Dailes teātrī 5. septembrī] /"

In [74]:
# original_data_df["PRIEKŠMETS - ŽANRS - 2 (655)"].value_counts()

In [99]:
data_df.head(1)

,ID,Recenzents,Recenzents un gadi,Avots,Temats,Gads,Recenzijas virsraksts,Recenzētā darba autors,Recenzētā darba autors (600),Recenzētā darba autors un gadi (600),...,RECENZĒTĀ FILMA VAI IZRĀDE - 3 (630),RECENZĒTĀ FILMA VAI IZRĀDE - 4 (630),RECENZĒTĀ FILMA VAI IZRĀDE -2 (630),VALODAS KODS (041),ĢEOGRĀFISKAIS NOSAUKUMS (651),ĢEOGRĀFISKAIS NOSAUKUMS - 2 (651),ĢEOGRĀFISKAIS NOSAUKUMS - 3 (651),ĢEOGRĀFISKAIS NOSAUKUMS - 4 (651),ĢEOGRĀFISKAIS NOSAUKUMS - 5 (651),visas_personas
0,672515,Eva Mārtuža,Eva Mārtuža 1954-,Konteksts,Suiti,2020,"Man ir kauns, es to saku",Dace Priede,Dace Priede,Dace Priede 1954-,...,NaN,NaN,NaN,NaN,"$$aAlsunga (Kuldīgas novads, Latvija)",NaN,NaN,NaN,NaN,['Eva Mārtuža']

In [100]:
recenziju_tipu_skaits = (
    data_df
    .groupby("Recenzijas tips")
    .agg(skaits=("Recenzijas tips", "count"))
    .reset_index()
)
recenziju_tipu_skaits.sort_values(by="skaits", ascending=False)

                    Recenzijas tips  skaits
9                 Teātra recenzijas    3131
5            Literatūras recenzijas    3059
4              Kinofilmu recenzijas    2435
3                Izstāžu recenzijas     938
6                Mūzikas recenzijas     906
7                 Operas recenzijas     398
0             Apskati un recenzijas     335
1                 Baleta recenzijas      62
8  Televīzijas raidījumu recenzijas      49
2                  Dejas recenzijas      43

In [93]:
tipi = [
    "Teātra recenzijas",
    "Literatūras recenzijas",
    "Kinofilmu recenzijas",
    "Mūzikas recenzijas",
    "Izstāžu recenzijas",
    "Operas recenzijas",
]
time_series = []
for tips in tipi:
    time_series.append(
        data_df
        .query("`Recenzijas tips` == @tips")
        .groupby("Gads")
        .agg(
            skaits=("Recenzijas tips", "count"),
        )
        .reset_index()
        .rename(columns={"Gads": "gads"})
        .assign(recenzijas_tips=tips)
)

time_series = pd.concat(time_series, ignore_index=True)

In [94]:
import altair as alt

# Bar chart showing review type counts
bar_chart = alt.Chart(recenziju_tipu_skaits).mark_bar().add_selection(
    alt.selection_interval()
).encode(
    y=alt.Y('Recenzijas tips:N', 
            sort='-x'),  # Sort by count descending
    x=alt.X('skaits:Q'),
    # color=alt.Color('recenzijas_tips:N', 
                    # legend=None),
    tooltip=['Recenzijas tips:N', 'skaits:Q']
).properties(
    width=600,
    height=400,
).interactive()

bar_chart

/var/folders/ww/wjp3pnms1kzc2pfzj0tyl6zr0000gn/T/ipykernel_56796/15354209.py:4: AltairDeprecationWarning:
Deprecated since `altair=5.0.0`. Use add_params instead.
  bar_chart = alt.Chart(recenziju_tipu_skaits).mark_bar().add_selection(

alt.Chart(...)

In [96]:
# Line chart showing time series trends for each review type
line_chart = alt.Chart(time_series.query("gads >= 2015")).mark_line(
    strokeWidth=3,
    point=True
).encode(
    x=alt.X(
        'gads:O', 
        # title='gads',
        scale=alt.Scale(zero=False)
    ),
    y=alt.Y('skaits:Q', 
            scale=alt.Scale(zero=False)),
    color=alt.Color('recenzijas_tips:N'),
    # strokeDash=alt.StrokeDash('recenzijas_tips:N'),
    tooltip=['gads:O', 'skaits:Q', 'recenzijas_tips:N']
).properties(
    width=700,
    height=500,
).interactive()

line_chart

alt.Chart(...)

In [ ]:
# Combined visualization: Bar chart and line chart side by side
combined_chart = alt.hconcat(
    bar_chart,
    line_chart,
    spacing=50
).resolve_scale(
    color='independent'
).properties(
    title='Review Analysis: Distribution and Trends'
)

combined_chart

In [ ]:
# Alternative: Stacked area chart for better trend comparison
area_chart = alt.Chart(time_series).mark_area(
    opacity=0.7,
    stroke='white',
    strokeWidth=1
).encode(
    x=alt.X('gads:O', 
            title='Year',
            scale=alt.Scale(zero=False)),
    y=alt.Y('skaits:Q', 
            title='Number of Reviews',
            stack='normalize'),  # Normalize to show proportions
    color=alt.Color('recenzijas_tips:N', 
                    title='Review Type',
                    scale=alt.Scale(scheme='category20')),
    tooltip=['gads:O', 'skaits:Q', 'recenzijas_tips:N']
).properties(
    width=700,
    height=400,
    title='Proportional Review Trends Over Time'
).interactive()

area_chart

# Check filtered out data

In [37]:
filtered_out_df["PRIEKŠMETS - ŽANRS (655)_a"].isna().sum()

np.int64(38417)

In [85]:
_col = "PRIEKŠMETS - ŽANRS (655)_a"
filtered_out_df[_col].value_counts().head(20)

PRIEKŠMETS - ŽANRS (655)_a
Intervijas.                           4292
Izstādes.                             2045
Personālizstādes.                      887
Zinātniskie raksti.                    614
Kongresi, konferences utt.             252
Biogrāfijas.                            87
Latviešu esejas.                        83
Latviešu dokumentālā publicistika.      74
Grāmatu apskati.                        68
Teātra recenzijas.                      60
Dokumentālā publicistika.               43
Krājumi.                                33
Nekrologi.                              25
Latviešu dzeja.                         23
Kinofilmu recenzijas.                   10
Latviešu ceļojumu apraksti.              8
Latviešu atmiņas.                        7
Latviešu stāsti.                         6
Izstāžu recenzijas.                      6
Latviešu romāni.                         5
Name: count, dtype: int64

In [84]:
# filtered_out_df[filtered_out_df[_col] == "Izstādes."].iloc[1500]

In [52]:
filtered_out_df["PRIEKŠMETS - TEMATS (650)_a"].value_counts().head(50)

PRIEKŠMETS - TEMATS (650)_a
Koncerti (pasākums)                 3031
Teātra iestudējumi                  2607
Mūzikas festivāli                   1844
Fotogrāfija                         1045
Gleznotājas                          811
Mākslinieki                          786
Gleznotāji                           765
Amatierteātris                       752
Aktieri                              731
Televīzijas seriāli                  660
Dziedātājas                          631
Fotogrāfi                            629
Deju kolektīvi                       625
Kinofestivāli                        625
Mūzikas grupas                       565
Latvijas dokumentālās filmas.        557
Mākslas izstādes                     554
Aktrises                             552
Mākslinieces                         525
Spēlfilmas                           499
Muzeju izstādes                      457
Teātra producenti un režisori        444
Latvijas kinofilmas.                 443
Dziedātāji                           428
Mūziķi                               421
Komponisti                           394
Kinofilmu producenti un režisori     387
Teātra festivāli                     384
Koncertzāle "Lielais dzintars".      369
Koru kolektīvi                       348
Mākslas festivāli                    335
Mūzika                               322
Mūzikas konkursi                     292
Fotogrāfija.                         263
Kinofilmas                           253
Deju festivāli                       245
Rokdarbi                             238
Mūzikas mācību iestādes              227
Vokālās grupas                       215
Deju koncerti                        212
Muzeji                               203
Latviešu autores.                    193
Latviešu literatūra                  182
Īpašie pasākumi                      174
Fotogrāfes                           172
Komercizstādes                       171
Latviešu autori.                     167
Latviešu glezniecība.                166
Pianisti                             161
Latviešu dzeja                       159
Name: count, dtype: int64

In [51]:
filtered_out_df["PRIEKŠMETS - TEMATS (650)_a"].isna().sum()

np.int64(305)

In [46]:
pd.set_option('display.max_colwidth', None)
cols = [
    "AUTORS (100)_4",
    "RAKSTA NOSAUKUMS (245)_a", 
    "RAKSTA NOSAUKUMS (245)_b",
    "PRIEKŠMETS - ŽANRS (655)_a",
    "PRIEKŠMETS - ŽANRS (655)_x",
    "PRIEKŠMETS - TEMATS (650)_a",
    "filter_reason",
]
filtered_out_df[filtered_out_df["PRIEKŠMETS - TEMATS (650)_a"] == "Teātra iestudējumi"][cols]

,AUTORS (100)_4,RAKSTA NOSAUKUMS (245)_a,RAKSTA NOSAUKUMS (245)_b,PRIEKŠMETS - ŽANRS (655)_a,PRIEKŠMETS - ŽANRS (655)_x,PRIEKŠMETS - TEMATS (650)_a,filter_reason
46,re'v,Bezceļa stopētāji :,"[krievu dramaturga un scenārista Aleksandra Molčanova luga ""Pusslepkava"" (rež. Regnārs Vaivars) Dailes teātrī] /",Teātra recenzijas.,NaN,Teātra iestudējumi,Author type not 'aut' or 'rev'
761,NaN,Шанс на счастье :,"[о спектакле ""Она в отсутствии любви и смерти"" (режиссеры Андрей Гаркави, Татьяна Черковская) по одноим. пьесе рос. писателя Эдварда Радзинского в постановке арт-платформы ""Stadia"" в Риж. Малом театре] /",Teātra recenzijas.,NaN,Teātra iestudējumi,Author type not 'aut' or 'rev'
1165,NaN,Turpinājums izrādei :,[aktieru izteikumi par kritiķiem un kritiku] /,NaN,NaN,Teātra iestudējumi,Author type not 'aut' or 'rev'
1591,ive,Reiz bija profesionāls teātris Jelgavā :,[par Jelgavas profesionālajam teātrim velt. izstādi Ādolfa Alunāna Memoriālajā muzejā : saruna ar muzeja vadītāju] /,NaN,NaN,Teātra iestudējumi,Author type not 'aut' or 'rev'
2480,ive,"""Opera ir karaļu māksla"" :","[saruna ar Lietuvas Nacionālā operas un baleta teātra ģenerāldirektoru, operdziedātāju, komp., muzikālā teātra prod. : sakarā ar Latvijas Nacionālās operas un baleta un Lietuvas Nacionālā operas un baleta teātra apmaiņas viesizrādēm Rīgā un Viļņā] /",Intervijas.,NaN,Teātra iestudējumi,Author type not 'aut' or 'rev'
...,...,...,...,...,...,...,...
47163,aut,Blaumanis visu ir paredzējis :,[par jaunās teātra sezonas jauniestudējumiem Latvijas teātros] /,NaN,NaN,Teātra iestudējumi,"Not a review, book review, or history/criticism"
47164,aut,Draugi! Būs slikti! :,[par jaunās teātra sezonas jauniestudējumiem Latvijas teātros] /,NaN,NaN,Teātra iestudējumi,"Not a review, book review, or history/criticism"
47165,aut,"Straumēnu DNS ""Billītēs"" :","[par Cēsu Mazo teātri, izrādi ""Bezgalīgais ritums"" (režisore Liena Šmukste) pēc rakstnieka Edvarta Virzas poēmas ""Straumēni"" motīviem] /",NaN,NaN,Teātra iestudējumi,"Not a review, book review, or history/criticism"
47167,aut,No lībiešiem līdz kvadroberiem :,[par nevalstisko teātru gaidāmo sezonu] /,NaN,NaN,Teātra iestudējumi,"Not a review, book review, or history/criticism"
47168,aut,Skroderdienas Krāslavā: Blaumaņa gars dzīvo arī šodien :,"[par dramaturga Rūdolfa Blaumaņa lugas ""Skroderdienas Silmačos"" brīvdabas iestudējumu (režisors Gundars Silakaktiņš) Krāslavas estrādē] /",NaN,NaN,Teātra iestudējumi,"Not a review, book review, or history/criticism"

In [50]:
# Option 1: Set pandas display options to show all content
pd.set_option('display.max_columns', None)  # Show all columns
pd.set_option('display.max_colwidth', None)  # Show full content of each column
pd.set_option('display.width', None)  # Don't wrap output
pd.set_option('display.max_rows', None)  # Show all rows (if needed)

# Now try displaying the row again
filtered_out_df.iloc[1591]

AUTORS (100)_4                                                                                                                                                                                                        ive
AUTORS (100)_a                                                                                                                                                                                             Matīsa, Maija,
AUTORS (100)_c                                                                                                                                                                                                        NaN
AUTORS (100)_d                                                                                                                                                                                                      1957-
PAPILDRAKSTS (700)_4                                                                                                                                                                                                  com
PAPILDRAKSTS (700)_a                                                                                                                                                                                     Veilands, Uldis,
PAPILDRAKSTS (700)_c                                                                                                                                                                                                  NaN
PAPILDRAKSTS (700)_d                                                                                                                                                                                                1958-
PAPILDRAKSTS - 2 (700)_4                                                                                                                                                                                              NaN
PAPILDRAKSTS - 2 (700)_a                                                                                                                                                                                              NaN
PAPILDRAKSTS - 2 (700)_c                                                                                                                                                                                              NaN
PAPILDRAKSTS - 2 (700)_d                                                                                                                                                                                              NaN
RAKSTA NOSAUKUMS (245)_a                                                                                                                                                         Reiz bija profesionāls teātris Jelgavā :
RAKSTA NOSAUKUMS (245)_b                                                                             [par Jelgavas profesionālajam teātrim velt. izstādi Ādolfa Alunāna Memoriālajā muzejā : saruna ar muzeja vadītāju] /
RAKSTA NOSAUKUMS (245)_c                                                                                                                                                          Maija Matīsa ; pierakst. Uldis Veilands
RECENZĒTAIS IZDEVUMS (787)_a                                                                                                                                                                                          NaN
RECENZĒTAIS IZDEVUMS (787)_t                                                                                                                                                                                          NaN
RECENZĒTAIS IZDEVUMS (787)_d                                                                                                                                                                                          NaN
RECENZĒTAIS IZDEVUMS (500)_a                                                                                                                                                                                          NaN
RECENZĒTĀ FILMA VAI IZRĀDE (630)_a                                                                                                                                                                                    NaN
RECENZĒTĀ FILMA VAI IZRĀDE (630)_g                                                                                                                                                                                    NaN
RECENZĒTĀ FILMA VAI IZRĀDE (630)_f                                                                                                                                                                                    NaN
AVOTA NOSAUKUMS (773)_t                                                                                                                                                                                    Zemgales Ziņas
AVOTA NOSAUKUMS (773)_g                                                                                                                                                               Nr.12 (2017, 23.marts), 22.-23.lpp.
ELEKTRONISKĀ ADRESE (856)_u                                                                                                                                                              http://articleid.news.lv/6350598
PRIEKŠMETS - TEMATS (650)_a                                                                                                                                                                            Teātra iestudējumi
PRIEKŠMETS - ŽANRS (655)_a                                                                                                                                                                                            NaN
PRIEKŠMETS - ŽANRS (655)_x                                                                                                                                                                                            NaN
PRIEKŠMETS - INSTITŪCIJA (610)_a                                                                                                                                                                        Jelgavas teātris.
PRIEKŠMETS - INSTITŪCIJA (610)_g                                                                                                                                                                                      NaN
NEKONTROLĒTS PERSONAS VĀRDS (720)_4                                                                                                                                                                                   NaN
NEKONTROLĒTS PERSONAS VĀRDS (720)_a                                                                                                                                                                                   NaN
NEKONTROLĒTS PERSONAS VĀRDS (720)_c                                                                                                                                                                                   NaN
NEKONTROLĒTS PERSONAS VĀRDS (720)_d                                                                                                                                                                                   NaN
NEKONTROLĒTS PERSONAS VĀRDS - 2 (720)_4                                                                                                                                                                               NaN
NEKONTROLĒTS PERSONAS VĀRDS - 2 (720)_a                                                                                                                                                                               NaN
NEKONTROLĒTS PERSONAS VĀRDS - 2 (720)_c                                                                                                                                                                               NaN
NEKONTROLĒTS PERSONAS VĀRDS - 2 (720)_d                                                                                                                                                                               NaN
NEKONTROLĒTS PERSONAS VĀRDS - 3 (720)_4                                                                                                                                                                               NaN
NEKONTROLĒTS PERSONAS VĀRDS - 3 (720)_a                                                                                                                                                                               NaN
NEKONTROLĒTS PERSONAS VĀRDS - 3 (720)_d                                                                                                                                                                               NaN
NEKONTROLĒTS PERSONAS VĀRDS - 4 (720)_4                                                                                                                                                                               NaN
NEKONTROLĒTS PERSONAS VĀRDS - 4 (720)_a                                                                                                                                                                               NaN
NEKONTROLĒTS PERSONAS VĀRDS - 4 (720)_d                                                                                                                                                                               NaN
NEKONTROLĒTS PERSONAS VĀRDS - 5 (720)_4                                                                                                                                                                               NaN
NEKONTROLĒTS PERSONAS VĀRDS - 5 (720)_a                                                                                                                                                                               NaN
NEKONTROLĒTS PERSONAS VĀRDS - 5 (720)_d                                                                                                                                                                               NaN
ELEKTRONISKĀ ADRESE - 2 (856)                                                                                                                $$uhttp://www.zz.lv/laikraksta-arhivs/laikraksts/2017-03-23$$yTīmekļa vietne
ELEKTRONISKĀ ADRESE - 3 (856)              $$uhttps://dom.lndb.lv/data/obj/877087.html$$yPilns teksts$$y(PDF)$$zResurss pieejams Latvijas Nacionālajā digitālajā bibliotēkā (bez iespējas lejupielādēt)$$qapplication/pdf
GADS (008)                                                                                                                                                                                                           2017
ID                                                                                                                                                                                                                3817396
KODĒTS DATĒJUMS (904)                                                                                                                                                         $$a2017$$dA$$eP$$h03$$jP$$m23.marts$$nNr.12
LURSOFT ID (905)                                                                                                                                                                                               $$a6350598
NBA01-ID (001)                                                                                                                                                                                            NBA01-003817396
PAPILDRAKSTS - 3 (700)                                                                                                                                                                                                NaN
PAPILDRAKSTS - 4 (700)                                                                                                                                                                                                NaN
PAPILDRAKSTS - 5 (700)                                                                                                                                                                                                NaN
PRIEKŠMETAM PIEVIENOTĀ ENTĪTE (688)                                                                                                                                                                                   NaN
PRIEKŠMETAM PIEVIENOTĀ ENTĪTE - 2 (688)                                                                                                                                                                               NaN
PRIEKŠMETS - INSTITŪCIJA - 2 (610)                                                                                                                                                  $$aĀdolfa Alunāna memoriālais muzejs.
PRIEKŠMETS - INSTITŪCIJA - 2 (610)2                                                                                                                                                                                   NaN
PRIEKŠMETS - INSTITŪCIJA - 3 (610)                                                                                                                                                                                    NaN
PRIEKŠMETS - INSTITŪCIJA - 4 (610)                                                                                                                                                                                    NaN
PRIEKŠMETS - PASĀKUMS (611)                                                                                                                                                                                           NaN
PRIEKŠMETS - PASĀKUMS - 2 (611)                                                                                                                                                                                       NaN
PRIEKŠMETS - PASĀKUMS - 3 (611)                                                                                                                                                                                       NaN
PRIEKŠMETS - PASĀKUMS - 4 (611)                                                                                                                                                                                       NaN
PRIEKŠMETS - PERSONA (600)                                                                                                                                                               $$aSpertāls, Arvīds,$$d1897-1961
PRIEKŠMETS - PERSONA - 3 (600)                                                                                                                                                                                        NaN
PRIEKŠMETS - PERSONA - 4 (600)                                                                                                                                                                                        NaN
PRIEKŠMETS - PERSONA - 5 (600)                                                                                                                                                                                        NaN
PRIEKŠMETS - PERSONA 2 (600)                                                                                                                                                              $$aSpertāle, Marga,$$d1901-1986
PRIEKŠMETS - TEMATS - 3 (650)                                                                                                                                                                                         NaN
PRIEKŠMETS - TEMATS - 4 (650)                                                                                                                                                                                         NaN
PRIEKŠMETS - TEMATS - 5 (650)                                                                                                                                                                                         NaN
PRIEKŠMETS - TEMATS 2 (650)                                                                                                                                                                          $$aMākslas izstādes.
PRIEKŠMETS - ŽANRS - 2 (655)                                                                                                                                                                                          NaN
RECENZĒTAIS IZDEVUMS - 2 (787)                                                                                                                                                                                        NaN
RECENZĒTĀ FILMA VAI IZRĀDE - 2 (630)                                                                                                                                                                                  NaN
RECENZĒTĀ FILMA VAI IZRĀDE - 3 (630)                                                                                                                                                                                  NaN
RECENZĒTĀ FILMA VAI IZRĀDE - 4 (630)                                                                                                                                                                                  NaN
RECENZĒTĀ FILMA VAI IZRĀDE -2 (630)                                                                                                                                                                                   NaN
VALODAS KODS (041)                                                                                                                                                                                                 $$alav
ĢEOGRĀFISKAIS NOSAUKUMS (651)                                                                                                                                                                                         NaN
ĢEOGRĀFISKAIS NOSAUKUMS - 2 (651)                                                                                                                                                                                     NaN
ĢEOGRĀFISKAIS NOSAUKUMS - 3 (651)                                                                                                                                                                                     NaN
ĢEOGRĀFISKAIS NOSAUKUMS - 4 (651)                                                                                                                                                                                     NaN
ĢEOGRĀFISKAIS NOSAUKUMS - 5 (651)                                                                                                                                                                                     NaN
filter_reason                                                                                                                                                                              Author type not 'aut' or 'rev'
Name: 1591, dtype: object

In [86]:
_col = "RECENZĒTĀ FILMA VAI IZRĀDE (630)_g"
len(filtered_out_df[~filtered_out_df[_col].isna()])

2248

In [60]:
filtered_out_df[~filtered_out_df[_col].isna()][_col].value_counts()

RECENZĒTĀ FILMA VAI IZRĀDE (630)_g
(spēlfilma)                                                               1041
(televīzijas seriāls)                                                      278
(dokumentālā filma)                                                        229
(animācijas filma)                                                         191
(televīzijas programma)                                                     38
(kinofilma)                                                                 24
(elektroniskais resurss)                                                    22
(žurnāls)                                                                   15
(laikraksts)                                                                12
(teātra izrāde : Klāvs Mellis).                                             11
(teātra izrāde : Jānis Znotiņš).                                            10
(teātra izrāde : Jānis Kaijaks).                                             9
(teātra izrāde : Paula Pļavniece).                                           9
(teātra izrāde : Reinis Suhanovs).                                           9
(filmu straumēšanas platforma)                                               8
(teātra izrāde : Elmārs Seņkovs).                                            8
(teātra izrāde : Valters Sīlis).                                             7
(daudzsēriju filma)                                                          6
(teātra izrāde : Jurģis Lūsis).                                              6
(teātra izrāde : Alvis Hermanis).                                            6
(teātra izrāde : Viesturs Kairišs).                                          6
(teātra izrāde : Laura Groza).                                               5
(teātra izrāde : Diāna Kaijaka).                                             5
(teātra izrāde : Liena Šmukste).                                             5
(teātra izrāde : Henrijs Arājs).                                             5
(teātra izrāde : Inese Mičule).                                              5
(teātra izrāde)                                                              5
(dokumentāla filma)                                                          5
(spēlfima)                                                                   5
(teātra izrāde : Gatis Šmits).                                               4
(īsfilma)                                                                    4
(teātra izrāde : Rēzija Kalniņa).                                            4
(teātra izrāde : Gundars Silakaktiņš).                                       4
(teātra izrāde : Oļegs Šapošņikovs).                                         4
(teātra izrāde : Pēteris Krilovs).                                           4
(teātra izrāde : Māra Ķimele).                                               4
(teātra izrāde : Matīss Kaža).                                               4
(teātra izrāde : Viesturs Roziņš).                                           4
(teātra izrāde).                                                             4
(operas izrāde : Alvis Hermanis).                                            4
(teātra izrāde : Ola Mafālani).                                              4
(teātra izrāde : Matīss Budovskis).                                          4
(televīzijas raidījums)                                                      4
(teātra izrāde : Aiks Karapetjans).                                          3
(teātra izrāde : Linda Zaharova).                                            3
(operas izrāde : Makss Emanuels Cenčičs).                                    3
(teātra izrāde : Mārtiņš Eihe).                                              3
(teātra izrāde : Sergejs Golomazovs).                                        3
(teātra izrāde : Kristīne Krūze).                                            3
(teātra izrāde : Toms Treinis).                                              3
(teātra izrāde : Regnārs Vaivars).                                           3
(teātra izrāde : Valdis Lūriņš).                                             3
(teātra izrāde : Juris Rijnieks).                                            2
(teātra izrāde: Juris Kalniņš).                                              2
(radioprogramma)                                                             2
(teātra izrāde : Indra Roga).                                                2
(televīzijs programma)                                                       2
(teātra izrāde : Endīne Bērziņa).                                            2
(teātra izrāde : Rēzija Kalniņa, Voldemārs Rode).                            2
(teātra izrāde : Elīna Cērpa).                                               2
(teātra izrāde : Gita Skadiņa).                                              2
(teātra izrāde : Дмитрий Крымов).                                            2
(teātra izrāde : Reinis Boters).                                             2
(teātra izrāde : Mārtiņš Egliens).                                           2
(teātra izrāde : Linda Kalniņa).                                             2
(teātra izrāde : Edgars Kaufelds).                                           2
(operas izrāde : Kšištofs Varlikovskis).                                     2
(operas izrāde : Olivjē Fredžs).                                             2
(Dace Rukšāne)                                                               2
(Jānis Rainis)                                                               2
(operas izrāde : Vensāns Busārs).                                            2
(seriāls)                                                                    2
(teātra izrāde : Ene-Līsa Sempere, Tīts Ojaso).                              2
(kinofilmas)                                                                 2
(Reinis Kaudzīte, Matīss Kaudzīte)                                           2
(teātra izrāde : Andrejs Jarovojs).                                          2
(dokumentālā spēlfilma)                                                      2
(Nora Ikstena)                                                               2
(koncertfilma)                                                               2
(baleta izrāde : Aivars Leimanis).                                           2
(teātra izrāde : Lukašs Tvarkovskis).                                        2
(teātra izrāde : Ralfs Liepa).                                               2
(teātra izrāde : Matiass Hartmans).                                          2
(teātra izrāde : Aigars Apinis).                                             2
(Gunars Janovskis)                                                           2
(teātra izrāde : Roberts Dauburs).                                           2
(teātra izrāde : Voldemārs Varslavāns).                                      2
(teātra izrāde : Māris Korsietis).                                           2
(baleta izrāde : Veins Makgregors)                                           1
(dokumentālās filma)                                                         1
(teātra izrāde: Imants Strads).                                              1
(teātra izrāde : Arnolds Liniņš).                                            1
(teātra izrāde : Kristīne Kauliņa).                                          1
(teātra izrāde : Jurijs Butusovs).                                           1
(teātra izrāde : Aivars Ikšelis).                                            1
(teātra izrāde : Dmitrijs Krimovs).                                          1
(muzikālā kinofilma)                                                         1
(Irina Bogdane)                                                              1
(Vizma Belševica)                                                            1
(operas izrāde : Viesturs Kairišs).                                          1
(teātra izrāde : Dzintra Medne).                                             1
(teātra izrāde : Ivo van Hove).                                              1
(teātra izrāde : Franciska Kronfota).                                        1
(teātra izrāde : Edmunds Freibergs).                                         1
(operas izrāde : Marija-Eva Sinjerola).                                      1
(teātra izrāde : Intars Rešetins-Pētersons).                                 1
(izrāde)                                                                     1
(operas izrāde : Džanlika Falaski).                                          1
(teātra izrāde : Kārlis Neimanis)                                            1
(teātra izrāde : Dmitro Poļežais).                                           1
(operas izrāde : Mīkaels De Koks, Karme Portaseli).                          1
(teātra izrāde : Jānis Mazitāns).                                            1
(teātra izrāde : Sarmīte Zdanovska).                                         1
(teātra izrāde : Kārlis Neimanis).                                           1
(operas izrāde : Olivjē Pī).                                                 1
(teātra izrāde : Rodrigo Struka).                                            1
(teātra izrāde : Venta Vecumniece).                                          1
(operas izrāde : Guntis Gailītis).                                           1
(operas izrāde : Aiks Karapetjans).                                          1
(teātra izrāde : Alise Bulanova)                                             1
(teātra izrāde : Edmunds Freibergs)                                          1
(teātra izrāde : Inese Mičule)                                               1
(operas izrāde : Tatjana Girbača, Viviena Honholca).                         1
(teātra izrāde : Viesturs Meikšāns)                                          1
(teātra izrāde : Dmitrijs Petrenko).                                         1
(teātra izrāde : Vladislavs Nastavševs)                                      1
(teātra izrāde : Ilgonis Škāns).                                             1
(operas izrāde : Maikls Meiers).                                             1
(teātra izrāde : Krišjānis Salmiņš).                                         1
(teātra izrāde : Jurģis Spulenieks).                                         1
(teātra izrāde : Agris Grāmatnieks).                                         1
(teātra izrāde : Ziedīte Začeste)                                            1
(teātra izrāde : Andress Noormets)                                           1
(teātra izrāde : Vadims Bogdanovs).                                          1
(teātra izrāde : Gita Skadiņa)                                               1
(teātra izrāde : Imants Strads).                                             1
(teātra izrāde : Ināra Cakule).                                              1
(teātra izrāde : Zanda Strogonova, Daiva Gedviliene, Nerijus Gedmins).       1
(baleta izrāde : Žans Kristofs Lesāžs).                                      1
(teātra izrāde : Nellija Spūle).                                             1
(mūzikls)                                                                    1
(teātra izrāde : Māra Ulme).                                                 1
(teātra izrāde : Artūrs Areima).                                             1
(operas izrāde : Indra Roga).                                                1
(teātra izrāde : Regīna Deksne).                                             1
(teātra izrāde : Elīna Gediņa).                                              1
(teātra izrāde : Rihards Zelezņevs).                                         1
(teātra izrāde : Mārcis Broks).                                              1
(teātra izrāde : Kristīne Brīniņa).                                          1
(teātra izrāde : Elīza Dombrovska).                                          1
(baleta izrāde).                                                             1
(teātra izrāde : Anta Priedīte).                                             1
(radio programma)                                                            1
(sērija)                                                                     1
(baleta izrāde : Marija Simona Šimulinaite).                                 1
(teātra izrāde : Zane Bondare).                                              1
(baleta izrāde : Kenets Tindals).                                            1
(teātra izrāde : Jons Tertelis).                                             1
(televīzijas seriāli)                                                        1
(teātra izrāde : Gerds Lapoška).                                             1
(teātra izrāde : Rūdolfs Gediņš).                                            1
(teātra izrāde : Anna Abalkhina).                                            1
(teātra izrāde : Dace Pūce).                                                 1
(teātra izrāde : Ināra Slucka).                                              1
(operas izrāde)                                                              1
(operas izrāde : Laura Groza-Ķibere).                                        1
(teātra izrāde : Juris Jonelis).                                             1
(teātra izrāde : Juris Kalniņš).                                             1
(teātra izrāde : Andress Normetss).                                          1
(teātra izrāde : Kristīne Vītola).                                           1
(dokumentalā filma)                                                          1
(Jānis Jaunsudrabiņš)                                                        1
(spēlfilma).                                                                 1
(dokumentālo filmu cikls)                                                    1
(Māris Putniņš)                                                              1
(Pavao Krmpotić)                                                             1
(teātra izrāde : Aleksandrs Morfovs).                                        1
(teātra izrāde : Roberts Vilsons)                                            1
(teātra izrāde : Herberts Laukšteins).                                       1
(operas izrāde : Marija Eva Sinjerola).                                      1
(koncertuzvedums)                                                            1
(teātra izrāde : Aiva Birbele).                                              1
(teātra izrāde : Vija Blūzma)                                                1
(teātra izrāde : Larisa Merca).                                              1
(teātra izrāde : Vladislavs Troickis).                                       1
(teātra izrāde : Ģirts Krūmiņš).                                             1
(teātra izrāde : Alicja Borkowska).                                          1
(teātra izrāde : Aivars Pecka).                                              1
(teātra izrāde : Māris Korsiets)                                             1
(operas izrāde : Viesturs Meikšāns).                                         1
(teātra izrāde : Liena Šmukste)                                              1
(teātra izrāde : Vlads Troickis).                                            1
(teātra izrāde : Edīte Krasnopa).                                            1
(teātra izrāde : Dž.Dž. Džilindžers).                                        1
(teātra izrāde : Endīne Bērziņa)                                             1
(operas izrāde : Ulrihs Raše).                                               1
Name: count, dtype: int64

In [93]:
filtered_out_df[filtered_out_df[_col] == "(teātra izrāde : Regnārs Vaivars)."].iloc[0]

AUTORS (100)_4                                                                                                                       NaN
AUTORS (100)_a                                                                                                                       NaN
AUTORS (100)_c                                                                                                                       NaN
AUTORS (100)_d                                                                                                                       NaN
PAPILDRAKSTS (700)_4                                                                                                                 rev
PAPILDRAKSTS (700)_a                                                                                                        Kalna, Baiba
PAPILDRAKSTS (700)_c                                                                                                            Dr. art.
PAPILDRAKSTS (700)_d                                                                                                                 NaN
PAPILDRAKSTS - 2 (700)_4                                                                                                             rev
PAPILDRAKSTS - 2 (700)_a                                                                                                  Kļaviņa, Ilze,
PAPILDRAKSTS - 2 (700)_c                                                                                                             NaN
PAPILDRAKSTS - 2 (700)_d                                                                                                           1972-
RAKSTA NOSAUKUMS (245)_a                                                                                         Kvests bez izlaušanās :
RAKSTA NOSAUKUMS (245)_b                   [izrāde "Suņu ciema Nelaimes lācis" (režisors Regnārs Vaivars) Latvijas Nacionālajā teātrī] /
RAKSTA NOSAUKUMS (245)_c                                                                                       Baiba Kalna, Ilze Kļaviņa
RECENZĒTAIS IZDEVUMS (787)_a                                                                                                         NaN
RECENZĒTAIS IZDEVUMS (787)_t                                                                                                         NaN
RECENZĒTAIS IZDEVUMS (787)_d                                                                                                         NaN
RECENZĒTAIS IZDEVUMS (500)_a                                                                                                         NaN
RECENZĒTĀ FILMA VAI IZRĀDE (630)_a                                                                             Suņu ciema Nelaimes lācis
RECENZĒTĀ FILMA VAI IZRĀDE (630)_g                                                                    (teātra izrāde : Regnārs Vaivars).
RECENZĒTĀ FILMA VAI IZRĀDE (630)_f                                                                                                2023.0
AVOTA NOSAUKUMS (773)_t                                                                                                       Kroders.lv
AVOTA NOSAUKUMS (773)_g                                                                                      (2023, 30. oktobris), 1 lp.
ELEKTRONISKĀ ADRESE (856)_u                                                                     http://dom.lndb.lv/data/obj/1306510.html
PRIEKŠMETS - TEMATS (650)_a                                                                                           Teātra iestudējumi
PRIEKŠMETS - ŽANRS (655)_a                                                                                            Teātra recenzijas.
PRIEKŠMETS - ŽANRS (655)_x                                                                                                           NaN
PRIEKŠMETS - INSTITŪCIJA (610)_a                                                                           Latvijas Nacionālais teātris.
PRIEKŠMETS - INSTITŪCIJA (610)_g                                                                                                     NaN
NEKONTROLĒTS PERSONAS VĀRDS (720)_4                                                                                                  NaN
NEKONTROLĒTS PERSONAS VĀRDS (720)_a                                                                                                  NaN
NEKONTROLĒTS PERSONAS VĀRDS (720)_c                                                                                                  NaN
NEKONTROLĒTS PERSONAS VĀRDS (720)_d                                                                                                  NaN
NEKONTROLĒTS PERSONAS VĀRDS - 2 (720)_4                                                                                              NaN
NEKONTROLĒTS PERSONAS VĀRDS - 2 (720)_a                                                                                              NaN
NEKONTROLĒTS PERSONAS VĀRDS - 2 (720)_c                                                                                              NaN
NEKONTROLĒTS PERSONAS VĀRDS - 2 (720)_d                                                                                              NaN
NEKONTROLĒTS PERSONAS VĀRDS - 3 (720)_4                                                                                              NaN
NEKONTROLĒTS PERSONAS VĀRDS - 3 (720)_a                                                                                              NaN
NEKONTROLĒTS PERSONAS VĀRDS - 3 (720)_d                                                                                              NaN
NEKONTROLĒTS PERSONAS VĀRDS - 4 (720)_4                                                                                              NaN
NEKONTROLĒTS PERSONAS VĀRDS - 4 (720)_a                                                                                              NaN
NEKONTROLĒTS PERSONAS VĀRDS - 4 (720)_d                                                                                              NaN
NEKONTROLĒTS PERSONAS VĀRDS - 5 (720)_4                                                                                              NaN
NEKONTROLĒTS PERSONAS VĀRDS - 5 (720)_a                                                                                              NaN
NEKONTROLĒTS PERSONAS VĀRDS - 5 (720)_d                                                                                              NaN
ELEKTRONISKĀ ADRESE - 2 (856)                                                                                                        NaN
ELEKTRONISKĀ ADRESE - 3 (856)                                                                                                        NaN
GADS (008)                                                                                                                          2023
ID                                                                                                                               4320644
KODĒTS DATĒJUMS (904)                                                                            $$a2023$$dW$$h11$$jW$$m30. oktobris$$eE
LURSOFT ID (905)                                                                                                                     NaN
NBA01-ID (001)                                                                                                           NBA01-004320644
PAPILDRAKSTS - 3 (700)                                                                                                               NaN
PAPILDRAKSTS - 4 (700)                                                                                                               NaN
PAPILDRAKSTS - 5 (700)                                                                                                               NaN
PRIEKŠMETAM PIEVIENOTĀ ENTĪTE (688)                                                                                                  NaN
PRIEKŠMETAM PIEVIENOTĀ ENTĪTE - 2 (688)                                                                                              NaN
PRIEKŠMETS - INSTITŪCIJA - 2 (610)                                                                                                   NaN
PRIEKŠMETS - INSTITŪCIJA - 2 (610)2                                                                                                  NaN
PRIEKŠMETS - INSTITŪCIJA - 3 (610)                                                                                                   NaN
PRIEKŠMETS - INSTITŪCIJA - 4 (610)                                                                                                   NaN
PRIEKŠMETS - PASĀKUMS (611)                                                                                                          NaN
PRIEKŠMETS - PASĀKUMS - 2 (611)                                                                                                      NaN
PRIEKŠMETS - PASĀKUMS - 3 (611)                                                                                                      NaN
PRIEKŠMETS - PASĀKUMS - 4 (611)                                                                                                      NaN
PRIEKŠMETS - PERSONA (600)                                                                                  $$aVaivars, Regnārs,$$d1973-
PRIEKŠMETS - PERSONA - 3 (600)                                                                                                       NaN
PRIEKŠMETS - PERSONA - 4 (600)                                                                                                       NaN
PRIEKŠMETS - PERSONA - 5 (600)                                                                                                       NaN
PRIEKŠMETS - PERSONA 2 (600)                                                                                                         NaN
PRIEKŠMETS - TEMATS - 3 (650)                                                                                                        NaN
PRIEKŠMETS - TEMATS - 4 (650)                                                                                                        NaN
PRIEKŠMETS - TEMATS - 5 (650)                                                                                                        NaN
PRIEKŠMETS - TEMATS 2 (650)                                                                                                          NaN
PRIEKŠMETS - ŽANRS - 2 (655)                                                                                                         NaN
RECENZĒTAIS IZDEVUMS - 2 (787)                                                                                                       NaN
RECENZĒTĀ FILMA VAI IZRĀDE - 2 (630)                                                                                                 NaN
RECENZĒTĀ FILMA VAI IZRĀDE - 3 (630)                                                                                                 NaN
RECENZĒTĀ FILMA VAI IZRĀDE - 4 (630)                                                                                                 NaN
RECENZĒTĀ FILMA VAI IZRĀDE -2 (630)                                                                                                  NaN
VALODAS KODS (041)                                                                                                                   NaN
ĢEOGRĀFISKAIS NOSAUKUMS (651)                                                                                                        NaN
ĢEOGRĀFISKAIS NOSAUKUMS - 2 (651)                                                                                                    NaN
ĢEOGRĀFISKAIS NOSAUKUMS - 3 (651)                                                                                                    NaN
ĢEOGRĀFISKAIS NOSAUKUMS - 4 (651)                                                                                                    NaN
ĢEOGRĀFISKAIS NOSAUKUMS - 5 (651)                                                                                                    NaN
filter_reason                                                                                             Author type not 'aut' or 'rev'
Name: 5813, dtype: object